### ISSUE TITLE
FunctionName tooltip text is too long - overflows the top border

### ISSUE THREAD

**Issue by khanzadyan** [elasticio/aws-lambda-component#4]
`FunctionName` parameter `note` description is too long it causes the tooltip to overflows and cut from above. I don't think this is a problem of `note` parameter general rendering class but with the length of the provided text.
![screen shot 2017-10-02 at 18 19 01](https://user-images.githubusercontent.com/11753582/31087843-dd886d98-a79e-11e7-9ffe-d6859bad5ad9.png)

**Comment by khanzadyan** [comment]
@zubairov I guess this should be sent your way.

**Comment by zubairov** [comment]
@khanzadyan  no, please send it to ``frontend`` as we need to make sure information in note is shown to the user properly. Thanks.

**Comment by khanzadyan** [comment]
@zubairov IMHO the information in note part should have some limit. No matter what solution is provided in frontend if the text is too long then this will be affected.

**Comment by zubairov** [comment]
Agree on the limit, but If ``frontend`` would be clever enough to place the tooltip in question **below** the question mark and not above it then it would work well - limit should be large enough.
